version: '3.7'

services:
  loader:
    build: .
    volumes:
      - ~/youtubeupload/:/app
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
    command: python3 /app/loader.py
    depends_on:
      - db

  db:
    image: postgres:11.4
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
